---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockup-api
  labels:
    app: backend
    project: demo
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: api
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
      - name: mockup-api
        image: opsta/mockup-api:dev01
        ports:
        - containerPort: 3000